Fix compatibility issues with ItemEditor.add_view
ItemEditor needs to be called with add_view(request, **kwargs). If
called with add_view(request, form_url, extra_context) it raises
TypeError: add_view() takes 2 positional arguments but 4 were given.