Support **kwargs in index_queryset
Running a site using this indexer gives the following error:

>  TypeError: index_queryset() got an unexpected keyword argument 'using'

We need to add `using=None` or `**kwargs` to `index_queryset` to avoid it.